version: "3"

services:
  web:
    build: .
    container_name: task_web
    command: bash ./bashes/RunBash.sh
    restart: always
    volumes:
      - .:/task/src
      - ./static_volume:/task/static
      - ./media_volume:/task/media
    depends_on:
      postgres_db:
        condition: service_healthy
    ports:
      - "8000:8000"


  postgres_db:
    image: postgres:12-alpine
    container_name: task_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tasksecret
      - POSTGRES_DB=cms
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cms"]
      interval: 10s
      timeout: 5s
      retries: 5